// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rent_A_House.Models;

namespace Rent_A_House.Migrations
{
    [DbContext(typeof(Rent_A_HouseDatabaseContext))]
    [Migration("20191022095106_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rent_A_House.BusinessLayer.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HouseId");

                    b.Property<decimal>("RentPerWeek");

                    b.Property<int>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.HasIndex("TenantId");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("Rent_A_House.BusinessLayer.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HouseAddress");

                    b.Property<int>("HouseOwnerId");

                    b.HasKey("Id");

                    b.HasIndex("HouseOwnerId");

                    b.ToTable("House");
                });

            modelBuilder.Entity("Rent_A_House.BusinessLayer.HouseOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactNumber");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("HouseOwner");
                });

            modelBuilder.Entity("Rent_A_House.BusinessLayer.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactNumber");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Tenant");
                });

            modelBuilder.Entity("Rent_A_House.BusinessLayer.Contract", b =>
                {
                    b.HasOne("Rent_A_House.BusinessLayer.House", "House")
                        .WithMany()
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Rent_A_House.BusinessLayer.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Rent_A_House.BusinessLayer.House", b =>
                {
                    b.HasOne("Rent_A_House.BusinessLayer.HouseOwner", "HouseOwner")
                        .WithMany()
                        .HasForeignKey("HouseOwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
